language: python

python:
  - "2.7"

sudo: false

install:
  - pip install -r requirements.txt

script:
  - cd docs; sphinx-build -nW -b html -d _build/doctrees . _build/html

notifications:
  email: false
