language: python

python:
  - "2.7"

sudo: false

install:
  - pip install -r requirements.txt

script:
  - mkdir docs/_static; cd docs; sphinx-build -nW -b html -D exclude_patterns=dev/docs/templates/*  -d _build/doctrees . _build/html

notifications:
  email: false
